build:
  steps:
    - name: Install Python packages and ngrok
      cmd: |
        python3 -m pip install notebook && \
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz && \
        tar -xvf ngrok-v3-stable-linux-amd64.tgz && \
        ./ngrok authtoken <your_ngrok_auth_token> && \
        ./ngrok http 8888 &
start:
  cmd: python3 -m notebook --allow-root
